spring:

  datasource:
    url: jdbc:mysql://localhost:3306/flashcards
    username: root
    password: 27111995

  sql:
    init:
      mode: always

  jpa:
    show-sql: true

  servlet:
    path:
      base: /api/v1
      categories: ${spring.servlet.path.base}/categories
      flashcards: ${spring.servlet.path.base}/flashcards
      study-sessions: ${spring.servlet.path.base}/study-sessions